# Generated by Django 5.1.4 on 2025-04-15 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('scname', models.CharField(max_length=100)),
                ('sclocation', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('stlocation', models.CharField(max_length=100)),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.schoolinfo')),
            ],
        ),
    ]
